# Documentation: https://github.com/roots/trellis#wordpress-sites
wordpress_sites:
  example.com:
    site_hosts:
      - howardbrown.dev
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:roots/bedrock.git
    site_install: true
    site_title: Example Site
    admin_user: admin
    admin_password: password
    admin_email: kbleich@thisisdk.com
    multisite:
      enabled: false
      subdomains: false
    ssl:
      enabled: false
    cache:
      enabled: false
      duration: 30s
    system_cron: true
    env:
      wp_home: http://howardbrown.dev
      wp_siteurl: http://howardbrown.dev/wp
      wp_env: development
      db_name: wordpress_hb_dev
      db_user: root
      db_password: root
